apiVersion: v2
name: victoriametrics
description: Wrapper chart for victoriametrics
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: victoria-metrics-single
    version: 0.18.0
    repository: https://victoriametrics.github.io/helm-charts/
